package org.rasterfun.ui.preview;

/**
 * Arranges pictures generated by one PictureGenerator for viewing.
 * E.g. in grid, or tiling endless mapping, or perspective projected tiling view.
 */
public interface PictureArranger {
}
